baseURL = "https://2bo.dev/"
title = "2bo.dev 開発者ブログ"
languageCode = "ja-jp"


paginate = 5

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  description = "2bo.dev - 月1アプリ開発で学んだ技術ノウハウ"
  images = ["/images/og-image.png"]

[markup]
  [markup.highlight]
    style = "github"

[mediaTypes]
  [mediaTypes."application/rss+xml"]
    suffixes = ["xml"]

[outputFormats]
  [outputFormats.RSS]
    mediaType = "application/rss+xml"
    baseName = "rss"
